### ISSUE TITLE
Solo Scenarios

### ISSUE THREAD

**Issue by hobnob** [PurpleKingdomGames/virtual-gloomhaven-board#34]
**Describe the new feature you'd like**
A while back Solo Scenarios were released that granted players additional loot. While this isn't remote play in the traditional sense (e.g. only one person is playing) I can see a situation where one person has Gloomhaven, but others in their party don't and would like to do the random scenario.

- [x] Complete Solo Scenario Loading
- [x] Brute
- [x] Tnkerer
- [x] Scoundrel
- [x] Cragheart
- [x] Mindthief
- [x] Spellweaver
- [x] Phoenix Face
- [x] Lightning Bolt
- [x] Angry Face
- [x] Triforce
- [x] Eclipse
- [x] Cthulhu
- [x] Three Spears
- [x] Saw
- [x] Music Note
- [x] Concentric Circles
- [x] Sun
- [x] Diviner

**Comment by luksan47** [comment]
Hey, thanks for your app, it looks great!
I'd be happy to help out with this issue, I think it would be especially useful to have this now, as these times it's even harder to meet and lend parts of the game for a solo scenario.

**Comment by hobnob** [comment]
Hi @luksan47 ,

That would be great :-) Another person is currently helping with these but I haven't had the PR through yet so I've been unable to test it. I'll need to get some underlying changes done before thses scenarios can be added (I'll need a drop-down for solo scenarios and then another drop down for the type of scenario). Once that's in I'll update this issue and we'll figure out which scenarios need doing. My aim is to get this finished by the second week in January 🤞

**Comment by luksan47** [comment]
Sounds good, I'll have plenty of free time during the holidays to work on this.

I think we could do the work in parallel, I could start preparing the json files and get myself familiar with the code while you prepare the scenario selector.
Some other issues might come up, so far I have noticed that the monster levels are set like this, the logic here should also be updated:
```
"twoPlayer": "normal",
"threePlayer": "normal",
"fourPlayer": "normal"
```
I think the most straightforward solution is to add a "onePlayer" field.

If it's okay for you, we could discuss and share the work to be done here. I can also work on a fork so you can check my progress for more transparency.

**Comment by hobnob** [comment]
No need for a `onePlayer` option I don't think - as it will just default to `twoPlayer` when there is 2 or less players present :-)

I'm going to be pretty busy from now until the end of the year, so I'm not expecting to make a proper start until the first week of January really. The plan is to have each solo scenario load from a `wwwroot/data/solo` directory, which will contain scenarios numbered 1 - 17 in order that they're given in the solo scenario PDF (so Brute is 1, Tinkerer is 2 etc.).

Until I've done the initial setup solo scenarios are going to be hard (but not impossible) to test. If you want to start off doing a few that would be great. You can overwrite the existing scenarios with the new solo ones, and then I can just port them when I have the solo scenario drop-downs working correctly :-) Happy for you to start from the top and work down. Another person is also helping and they've done Cthulu so far, so we can steer clear of that for the moment. When I'm ready to start on the scenarios proper I'll update here and let you know - I'm hoping I can work at a rate of about 2 - 3 scenarios a day once I get going as they aren't complicated setups.

In order to get the scenarios working you can use `run.sh` on Mac or Linux to get the server up and running locally. There's currently no similar function for Windows, but you can try copying the command in `run.sh` to the command line and see if it works (it didn't for me, and I didn't have enough time to figure out why). I recently set out a useful list for making scenarios, so this might help:

 - Each map tile is a grid of x,y coordinates starting at 0,0 (top, left) and working right to bottom from there
 - The exception is the 'a' map tiles, which start at 0,1 but that's the only exception
- The hex-grid is Odd-Row. That is to say that every odd row (1,3,5 etc) is offset to the right of even rows (see here for examples: https://www.redblobgames.com/grids/hexagons/#coordinates-offset )
 - You can place tiles outside of the grid (-1, -1 for example) and that's fine
 - Corridors are tricky business - stick to single size corridors ("size": 1), as size 2 are poorly implemented
 - The last room wins - that's to say if you have multiple doors leading to the same room then the last door you code will take precedents over all other doors leading to that room
 - Turning the tile doesn't affect the grid reference 0,0 is always the same point on the tile
 - As a general rule for a new scenario start with a copy of template.json and work from there, I just find it easier


Hopefully that all helps ... If you have any other qustions let me know :-)

**Comment by luksan47** [comment]
Thanks for the detailed description and the tips!

I've already got my working local copy and played around with creating a scenario, I'm almost done with music note (last room missing). Getting the doors right was the trickiest to figure out here. For now, I've just added it is as scenario#116, when you are done, we can move it to its place.

What I could not figure out however is turning. I wanted to turn the b1a tile (starting tile) like in the scenario book, but did not manage to get it right, so for now, went with a rotated version. Pushed my changes so far here, if you could take a look sometime (no hurries):
https://github.com/luksan47/virtual-gloomhaven-board/tree/solo

I'd also create the ones for sun and three spears next.

**Comment by luksan47** [comment]
> No need for a onePlayer option I don't think - as it will just default to twoPlayer when there is 2 or less players present :-)

Yeah, right, made a mistake there when I first tried, thanks, it's working now! :)

**Comment by hobnob** [comment]
> What I could not figure out however is turning.
Turning is a little tricky. There's 2 properties when you initially look at the JSON `angle` and `turns`. You only need to worry about `turns`, as `angle` is currently ignored.

`turns` are the number of times a map tile is rotated clockwise so that the top of the hexagon is a point. This is a number between 0 (no additional rotation compared to the original image) and 5. The rotation occurs around the point of origin, which is to say that if it's the first map tile the rotation will be around the top left corner, and if the tile is linked to a door or corridor then the map tile will be rotated around that door.

Hope that helps! :-)

**Comment by hobnob** [comment]
Probably also worth adding that we only use pointy hexagons, so if the scenario book has a scenario with flat hexagons it won't be possible to align it completely at the moment

**Comment by luksan47** [comment]
> Probably also worth adding that we only use pointy hexagons, so if the scenario book has a scenario with flat hexagons it won't be possible to align it completely at the moment

I see, I think this is the case for me. Thanks! Then now I think I'm done with music note.

Let's track the solo scenarios here:

- [ ] brute
- [ ] tinkerer
- [ ] scoundrel
- [ ] cragheart
- [ ] mindthief
- [ ] spellweaver
- [ ] phoenix-face
- [ ] lightning-bolt
- [ ] angry-face
- [ ] triforce (WIP)
- [ ] eclipse
- [x] cthulhu
- [ ] three-spears
- [ ] saw
- [x] music-note
- [ ] concentric-circles
- [ ] sun (WIP)

**Comment by hobnob** [comment]
A good idea! I've added it to the main issue text so I can earier keep up with what's been added at a glance

**Comment by luksan47** [comment]
Cool! I can't check that one though, so I think I'll use mine and we can occasionally sync the checklists?

**Comment by hobnob** [comment]
Sounds like a plan :-)

**Comment by luksan47** [comment]
Hey @hobnob,
finished the solo scenarios for the base game, opened PR https://github.com/PurpleKingdomGames/virtual-gloomhaven-board/pull/59
I currently do not have the diviner solo scenario, so I could not include it now.

**Comment by hobnob** [comment]
Hi @luksan47 ,

That's amazing work, thank you so much! I'll have a look at the PR at some point in the next week and get the rest of the work complete for solo scenarios, but this has helped loads, thank you!

**Comment by hobnob** [comment]
Added to release [v1.9.0](https://github.com/PurpleKingdomGames/virtual-gloomhaven-board/releases/tag/v1.9.0)
