### ISSUE TITLE
Custom Summons

### ISSUE THREAD

**Issue by hobnob** [PurpleKingdomGames/virtual-gloomhaven-board#42]
**Describe the new feature you'd like**
Summons are currently the standard purple that comes with Gloomhaven, but it would be nice to customise them into any colour, and to assign them a new number. Less confusion, and a better experience

**Comment by luksan47** [comment]
Hi @hobnob,
if nobody is working on this issue, I'd give it a try.
Do you have some ideas where can we get the other summon icons?

**Comment by hobnob** [comment]
Hi @luksan47 

No one's working on this one at the moment. I currently don't know where we can get hold of the other summons icons, but I had a plan in mind that might not need them. My current thinking is that we could create a mask image for summons by making it greyscale, similar to the icon we use in the menu. We could then use CSS to change the colour to anything we want (in theory), which would mean we wouldn't need additional assets.

The other thing I was thinking was that a player should be able to change the colour of a summons from the side-bar. So they would select a colour for their summons (if they wanted a different colour) and then place it. This would reduce the number of icons in that side-bar, which is likely to grow. But as a start we could add additional icons and then change it later :-)

Hope that makes sense :-)

**Comment by luksan47** [comment]
Thanks for the ideas!
Masking the images sounds even better, yeah, I'll try that one.
I think I'll start with the simplest option for the selection and improve it incrementally.

**Comment by hobnob** [comment]
This might actually be as simple as 5 or so options for Summons (red, yellow, purple, blue, green)
