### ISSUE TITLE
Forgotten Circles support

### ISSUE THREAD

**Issue by bmull22** [PurpleKingdomGames/virtual-gloomhaven-board#46]
First, you're the bomb for putting this together. Great for when we already have the game but want to social distance.

Would it be possible to add support for Forgotten Circles? Mainly you just need the Diviner and an overlay tile for the rifts. Rifts would need to be able to be placed on any tile, even tiles with obstacles or characters, and always visible. I'm thinking something transparent and/or only covering part of a hex.

**Comment by hobnob** [comment]
Glad you like it :-) I'm surprised I haven't already got an issue raised for this to be honest, it makes complete sense to add it!

It might be worth doing a 2 phased approach to this:
 1) Add the assets you mentioned so people wanting to play Gloomhaven scenarios with the Diviner can (easy)
 2) Add the scenarios and any extra monster tiles for full support (harder, as I don't own the game yet)

The first part I *might* be able to squeeze into [1.6.0](https://github.com/PurpleKingdomGames/virtual-gloomhaven-board/milestone/5). The second will take considerably longer, but certainly is something I want to do :-)

**Comment by bmull22** [comment]
Yeah, that 2 phased approach would be good. In fact, we're just using the Diviner in base Gloomhaven at this point, so it would work perfectly for me. Another person in our party has FC, but I may be able to get the info from him and pass along to you.

**Comment by hobnob** [comment]
Should really have refernced this in the relevant commits :-/ It's now possible to select the Diviner as a player and, when they're in play, possible to add a Rift

Hope that helps for now... I'll start adding the scenarios in over the next few weeks.. so hopefully full support isn't too far behind :-)
