### ISSUE TITLE
Randomize the monster numbers

### ISSUE THREAD

**Issue by amusedleg** [PurpleKingdomGames/virtual-gloomhaven-board#47]
A small request: please randomize (or provide a button) the monster numbers in a given room.  In a crowded scenario like Forgotten Sewers it can have a pretty big impact.

**Comment by hobnob** [comment]
Hi @amusedleg , the monster numbers should already be randomly assigned. Is this not what you're seeing?
What *should* happen is that as you add a monster or reveal a room the first available number should be taken from a randomised list of possible numbers for that monster type. When a monster is defeated this number is then added back to the stack, ready to be re-used. Are you seeing different behaviour? Or is there an alternative way you'd like to see monster numbers being distributed?

**Comment by hobnob** [comment]
Closing this until there's more info
