### ISSUE TITLE
The number of monsters does not change with player count

### ISSUE THREAD

**Issue by amusedleg** [PurpleKingdomGames/virtual-gloomhaven-board#48]
I found that when I changed the number of characters the number and type of monsters did not change.  Is that intentional?  Or is that a bug?  I am not sure.

**Comment by hobnob** [comment]
Hi @amusedleg , it certainly should change 🙁 

Can you let me know what scenario you were playing, and what number of players you changed from and to?

**Comment by hobnob** [comment]
Closing this until there's more info
