### ISSUE TITLE
Scroll to first available tile on map load

### ISSUE THREAD

**Issue by sickDevelopers** [PurpleKingdomGames/virtual-gloomhaven-board#49]
Hello, thank you for the effort you're putting on this.

It will be very nice, especially for long vertical maps that starts at the bottom, to scroll to the first visible tile on page load. 

Thank you

**Comment by hobnob** [comment]
Hi @sickDevelopers 

Thanks for the thought :-) Definitely worth doing I think.. I'll keep you posted on when it might be available :-)
