### ISSUE TITLE
Tooltip text behind menu

### ISSUE THREAD

**Issue by bmull22** [PurpleKingdomGames/virtual-gloomhaven-board#51]
**Affected Scenario(s):** 
All?

**Describe the bug**
The tooltip text for the command/menu icons on the left is behind the menu.

**To Reproduce**
1. Open the game in-browser.
2. Note tooltip text. See attached GIF.
![2020-11-15_22-14-46](https://user-images.githubusercontent.com/73444318/99212184-0e158f80-2790-11eb-8266-0237381f6f2f.gif)

**Browser :** Chrome, Edge, haven't tried others.

**Comment by hobnob** [comment]
Thanks for letting me know :-) Not quite sure where this crept in, but it should be fixed now :-)
