### ISSUE TITLE
Duplicate monster tile when 2 people move the same monster

### ISSUE THREAD

**Issue by cboucher-cghy** [PurpleKingdomGames/virtual-gloomhaven-board#52]
**Affected Scenario(s):** [e.g. 6, 10 and 33]
43
**Describe the bug**
Duplicate a monster tile when two people move the same monster at the same time to a different location.

**To Reproduce**
1. Go to the second room
2. One person move a flame demon 
3. While the drag and drop is active by the first player, move the same flame demon by a second player to another location (different of the first player)
4. See the error where a duplicate monster tile appears

Note: Undo is possible to avoid the problem.

**Browser :** [e.g. Chrome, Firefox]
Both players used Chrome

**Comment by hobnob** [comment]
This one's a bit tricky - for monsters and characters is relatively trivial as we could easily remove a monster by id/type and the characters in the same way.

But this issue extends beyond just monster/character moevment - in theory it also relates to adding monsters + overlays, as well as moving overlays, which currently don't have a unique identifier. In the first instance we probably need a validation step to make sure the same monster hasn't already been moved. We would then need unique identifiers for overlays so we can do the same thing there too 🤔

**Comment by hobnob** [comment]
Sorry this is a bit late coming, this should now be fixed :-)

**Comment by cboucher-cghy** [comment]
> Sorry this is a bit late coming, this should now be fixed :-)

Way to go! As always, "better late than never" ;) 

Even if this wasn't a blocker issue and we have a workaround, it will enhance the overall experience of this app. Thank you for fixing it!
