### ISSUE TITLE
Unable to move anything

### ISSUE THREAD

**Issue by glenn-fredrx** [PurpleKingdomGames/virtual-gloomhaven-board#53]
**Affected Scenario(s):** All

**Describe the bug**
Unable to move any objects anymore starting today.  Even though I have the boot icon selected, I can't move any characters or monsters.

**To Reproduce**

**Browser :** 
Issue in both Chrome and Edge

**Comment by hobnob** [comment]
Thanks for raising this @glenn-fredrx ! I actually ended up replying to issue #54 before this one, but they are the same problem :-( 

As mentioned there, this will be fixed soon.. I'm really sorry about the inconvenience this has caused you

**Comment by hobnob** [comment]
I've managed to roll out a fix for this now (1.6.2) - You will be able to tell if you're running the current version by looking in the bottom right of the screen, where it should say 'Version 1.6.2'. You may need to do a hard refresh or clear your cache in order for it to work properly.

I'm really sorry it was down for so long

**Comment by glenn-fredrx** [comment]
It is working now.  Thanks for the quick turn around on this.  I have to say a huge amount of thanks on building this app.  It is great and saves me a ton of time.  I had been building scenario maps in Vision in order to run our gloomhaven campaign.

**Comment by hobnob** [comment]
No problem, I'm really glad you're enjoying it :-)
