### ISSUE TITLE
'Move' action not possible in Chrome

### ISSUE THREAD

**Issue by radekwyrwas** [PurpleKingdomGames/virtual-gloomhaven-board#54]
**Affected Scenario(s):** [e.g. 6, 10 and 33]
4, 16 and 18 are the only three I tried but my hunch is that all of them might be affected

**Describe the bug**
Moving monsters or players does not work.

**To Reproduce**
1. Go to one of the scenarios listed above
2. Click on any monster or starting character
3. Try to perform the 'move' action
4. You will see that it does not work

**Browser :** 
It doesn't work in Chrome.
Firefox seems to work fine.

**Comment by hobnob** [comment]
Thanks for raising this @radekwyrwas ! Unfortunately a release late last night broke the move functionality in Chrome.. I should have a fix for this rolled out soon though.

Really sorry about the inconvenience this has caused

**Comment by hobnob** [comment]
I've managed to roll out a fix for this now (1.6.2) - You will be able to tell if you're running the current version by looking in the bottom right of the screen, where it should say 'Version 1.6.2'. You may need to do a hard refresh or clear your cache in order for it to work properly.

Sorry again for the trouble caused

**Comment by radekwyrwas** [comment]
Thank you so much!
