### ISSUE TITLE
Show terrain features beneath creatures

### ISSUE THREAD

**Issue by l0ft3r** [PurpleKingdomGames/virtual-gloomhaven-board#55]
**Describe the new feature you'd like**
It would be nice to be able to see that there is difficult terrain under a (flying) creature. This could be achieved, for example, by making the players and creatures 10% smaller, so that the coloured boundaries of the underlying tile becomes visible.

Scenario 91 used as an example:
![image](https://user-images.githubusercontent.com/2506418/102094969-3b9f3880-3e23-11eb-971b-c1d79ef5e299.png)

Scenario 59 used as an example:
![image](https://user-images.githubusercontent.com/2506418/102095198-87ea7880-3e23-11eb-8c64-eb81e4a7d3ec.png)

**Comment by hobnob** [comment]
Not really sure why I didn't think of this one! :-) A great idea, and now available in this release (1.8.0)
