### ISSUE TITLE
Tree overlay hides monster number

### ISSUE THREAD

**Issue by l0ft3r** [PurpleKingdomGames/virtual-gloomhaven-board#56]
**Affected Scenario(s):** [59 and all scenarios with trees and (flyin creatures or players)]

**Describe the bug**
The number of the monster is hidden when it is flying over a tree overlay tile.

**To Reproduce**
1. Start scenario 59
2. Move an Imp (or any monster) onto a tree.
3. Note that the number of the monster is no longer visible.

**Browser :** Chrome

Scenario 59 used as an example
![image](https://user-images.githubusercontent.com/2506418/102095984-7655a080-3e24-11eb-8caf-71056257d2a0.png)

**Comment by hobnob** [comment]
Should definitely fix this! I'll add it to the next release :-)
