### ISSUE TITLE
Monster Missing in Scenario 2

### ISSUE THREAD

**Issue by radekwyrwas** [PurpleKingdomGames/virtual-gloomhaven-board#57]
**Affected Scenario(s):** [e.g. 6, 10 and 33]
Scenario 22

**Describe the bug**
Flame Demon missing from the top right corner room D1a tile in a two player game

**To Reproduce**
1. Go to Scenario 22 and set it up for 2 players
2. Open room on the top right
3. See that there are no monsters in it

**Browser :** [e.g. Chrome, Firefox]
Google Chrome is up to date
Version 87.0.4280.88 (Official Build) (64-bit)
![22_monster_missing](https://user-images.githubusercontent.com/3092403/102310112-50212500-3f38-11eb-9191-5da42981bb0f.png)

**Comment by hobnob** [comment]
Thanks for letting me know @radekwyrwas ... All sorted :-)
