### ISSUE TITLE
Rift Tokens (Forgotten Circles)

### ISSUE THREAD

**Issue by jeffsimmons86** [PurpleKingdomGames/virtual-gloomhaven-board#61]
**Affected Scenario(s):** 96 and all FC scenarios

**Describe the bug**
Once a Rift Token is placed it cannot be moved or removed.  Ethereal Vortex card allows these to be moved, but we are unable to using either the move character function or move obstacle or trap function.

**To Reproduce**
Place rift token, try and move or remove it.

**Browser :** Chrome

**Comment by hobnob** [comment]
This is a two part issue really - the first is that Rifts can't be removed, and the second is that obstacles overall can't be moved in Chrome.

Rifts are now removable! 🎉  This should sidestep the second issue, but doesn't fix it.
The second issue is more widespread and something I've been looking into for quite some time. A release of Chrome seems to have caused all obstacles to no longer be draggable. Despite my best efforts I can't see any reason why this would be the case when monsters and characters (which are semantically the same as overlays) are not affected.

I'm going to keep this open until I can find a fix for Chrome or until Google fix it themselves, but at least there's a workaround now.

**Comment by jeffsimmons86** [comment]
Thanks for the update!  Your board had been a huge help allowing you group
to play during COVID and from different states in the US. We used to set a
camera up over the board but that obviously left one person moving
characters and monsters.

**Comment by hobnob** [comment]
No problem! Really glad you're enjoying it - hopefully that Chrome bug won't be too troublesome until I can get a fix 🙂
