### ISSUE TITLE
Can't remove water tile on scenario 74

### ISSUE THREAD

**Issue by superchuck8** [PurpleKingdomGames/virtual-gloomhaven-board#65]
**Affected Scenario(s):** [e.g. 6, 10 and 33]
74

**Describe the bug**
In this scenario we need to add/remove water tile as the game goes. We can remove water tile by using loot action. However, there is no way to remove those tiles in the app.

**To Reproduce**
1. Launch scenario 74
2. Add a water tile
3. Try to remove it...

1. Launch scenario 74
2. Immediately try to remove a water tile.

**Browser :** [e.g. Chrome, Firefox]
Chrome Version 88.0.4324.182

**Comment by hobnob** [comment]
I'll have a look into this one and see if I can find a fix for it.. the release has been really late this time around as I've been working on creating custom scenarios. But I'll try and get it inot the next realease as soon as it's ready
