### ISSUE TITLE
Add Letter/Numbers to the Gloomhaven Board

### ISSUE THREAD

**Issue by Gritchu** [PurpleKingdomGames/virtual-gloomhaven-board#66]
**Is your feature request related to a problem? Please describe.**
Today my group did Scenario 70. This map in the official Gloomhaven book has letters that enemies spawn at each round and a number on the final door to read the additional text once the door is opened. We could not find any way to add those letters/numbers to the map. We saw that we could put down a water tile using the summons button. SO we did that in place of the letter A and B so we could remember where the enemies spawned each round. As we played we actually forgot that there was text to read upon opening the final door and didn't read that until the scenario was over.

**Describe the new feature you'd like**
We would like a new menu tool/button that would present a list of letters and numbers we could add to the tiles. It would function similarly to the Summons button in terms of the slide-out menu with the letters/numbers. Dragging them onto a tile/map would then behave like the loot icons (perhaps showing up on the left as the loot is on the right when that tile is occupied by an enemy or player). This way we can remember important information needed for the game.

We love this service as it helps us play remotely with a friend that we haven't gotten together with since COVID began. We hope to see new features and usability improvements as time goes on. Thank you.

**Comment by hobnob** [comment]
Thanks for getting in touch @Gritchu ! This is definitely on the road map (see issue #60 )  and should be available in the next few months. Currently it's being held up by the scenario creator work, which I want to get finished first before moving back onto useability improvements for the main app. I'll keep this issue open, so you'll get notified once it's available :-)
