### ISSUE TITLE
Problems with Gloomhaven scenario 76 Harrower Hive

### ISSUE THREAD

**Issue by cafelizardo** [PurpleKingdomGames/virtual-gloomhaven-board#67]
**Affected Scenario(s):** 76

**Describe the bug**
* icon for Night Demon appears as Living Spirit.
* Treasure tile on tile A3a is labeled as 73, should be 75.

**To Reproduce**
1. Go to '76'
2. Open door to E1b 
3. See wrong monster icon displayed. It is correct on tile G2a
4. Go to furthest room and note number of the treasure tile.

**Browser :** 
Safari on Mac, similar problem on other browsers on other platforms reported by other players in same game.

**Comment by hobnob** [comment]
Thanks for letting me know - I'm looking to get a release out in the next couple of weeks, so I'll roll a fix into that :-)
