### ISSUE TITLE
Unable to remove initial water in scenario 74

### ISSUE THREAD

**Issue by cafelizardo** [PurpleKingdomGames/virtual-gloomhaven-board#68]
**Affected Scenario(s):** 
scenario 74 - Merchant Ship

**Describe the bug**
Scenario starts with water on tile B but unable to remove initial water tiles.  We can add and remove new single hex water tiles.  Work around was to "summon" other tiles to cover the purple tiles.

**To Reproduce**
1. Load scenario 74 which populates tile B with purple water tiles.
2. Unable to remove initial water tiles.

**Browser :** [e.g. Chrome, Firefox]
Safari, Chrome, and Safari.

**Comment by cafelizardo** [comment]
Duplicate of issue #65.
/close

**Comment by cafelizardo** [comment]
Hey I noticed that this is now fixed as of April 27th.  If you need help verifying bugs or corrections or anything I would be more than happy help out.  I have access to Safari on Mac, and Firefox and Chrome on both Windows and Mac.  I also have access to an Ipad and I believe an old Android tablet if needed as well.

**Comment by hobnob** [comment]
Thanks fo rthe offer @cafelizardo  :-D I'll definitely keep that in mind and let you know if I have anything! :-)
