### ISSUE TITLE
Provide ability to spawn vs summon monsters so they will automatically drop loot

### ISSUE THREAD

**Issue by cafelizardo** [PurpleKingdomGames/virtual-gloomhaven-board#69]
**Is your feature request related to a problem? Please describe.**

While playing scenario 74 "Merchant Ship" noticed that the spawned monsters do not drop loot because they were added by using the summon action.  

**Describe the new feature you'd like**

Work around is to remember to spawn a loot token when spawned monster is killed but it would be better to have the web app do this.  Possibly add another action icon on the left that behaves similar to the summon action but sets what ever flag is necessary to drop loot when it is killed.

**Comment by hobnob** [comment]
Hmmmm... that's a real pain. It would be nice if the app just dealt with it transparently rather than a player remembering to spawn rather than summon or vice versa. This probably won't make it into the next release, but shouldn't be a massive problem, so I'll add it soon after I think

**Comment by hobnob** [comment]
Fixed in [v1.12.0](https://github.com/PurpleKingdomGames/virtual-gloomhaven-board/releases/tag/1.12.0)
