### ISSUE TITLE
Unable to move or create barrels for Forgotten Circles #101

### ISSUE THREAD

**Issue by cafelizardo** [PurpleKingdomGames/virtual-gloomhaven-board#74]
**Affected Scenario(s):** [e.g. 6, 10 and 33]
101

**Describe the bug**
Forgotten Circle scenario 101 Shrouded Crypt, page 22 section 64 has Barrels that need to be moved.  There does not appear to be a way to move them and once you delete a Barrel you can't create a new one.

Also there is fog in the later rooms which need to be removed per description on page 24, section 72.  You can use the door action by clicking on the fog which reveals the next section of the map but the fox does not go away.  Same problem on  page 39 section 123

**To Reproduce**
1. Set scenario 101
2. Use open door mode and click on dark corridor on right edge which will expose the next room.  Try moving the barrels.
3. Only known workaround is to delete the barrel then spawn an object like the summon token which can then be moved.
4. Then click on door on left edge of newly exposed room to reveal the next room
5. Click on revealed fog/door to reveal next section, the fog/doors should be removed.  
6. Click on final fog/door to reveal the final section, again, the door/fog should be removed.

**Browser :** [e.g. Chrome, Firefox]

Confirmed on Safari 14.11 on Mac and Firefox 88.01 on Mac and on Windows

**Comment by hobnob** [comment]
Hi @cafelizardo !

You should be able to move the barrels by selecting the 'Move Obstacles and Traps' icon on the left (4th one down) and then dragging the barrel. There's an issue at the moment in Chrome that stops you moving obstacles this way, but Firefox should definitely be fine (just tested it in Firefox 90.0 on a Mac).

I'm working on a new interface at the moment that should make moving things, and placing things, better all around (which also includes adding barrels).

At the moment the fog in these rooms are simple doors. I have a couple of scenarios that need some custom logic (especially for Forgotten Circles, which seems to crank the compexity to 11), so I'll raise a seperate feature request for that so it doesn't get lost in the ether

Hope that helps 🙂
