### ISSUE TITLE
Unable to find some monsters to summon when list is too long

### ISSUE THREAD

**Issue by cafelizardo** [PurpleKingdomGames/virtual-gloomhaven-board#78]
**Affected Scenario(s):** [e.g. 6, 10 and 33]

Senario #103 from Forbidden Circles

**Describe the bug**

Senario #103 uses random monsters but the list is longer than the screen is tall so the list goes off the screen and you can't find some monsters.  For some we were able to select at the top of map to create the monster then drag to where we needed it   But for other monsters like the vermlin scout we could not find it.  Tried to use two monitors organized vertically but browser widow would not span vertically on Mac.

Also we needed to create the caravan but could not find anything suitable so we used the barrel.  Could not drag to move so we had to create a new barrel and remove the old one at the end of every turn. 

**To Reproduce**
1. Go to scenario 103.
2. Try to create a symbol for the caravan
3. Click on click on summon and you'll see that the list goes off the screen.  

**Browser :** [e.g. Chrome, Firefox]

Tried Safari, Chrome and Firefox on multiple platforms.

**Comment by hobnob** [comment]
Hi @cafelizardo , really sorry to hear about that - sounds like a rough way to play a scenario 😞 

I'll have a look at this and get a fix out as soon as possible for you. Sounds like the barrel situation is a Chrome bug that stops you moving obstacles - I'm actively looking at this, but I haven't found any reason yet why it doesn't work so it's an ongoing piece of work which I don't have any timeframe on yet 😕
