### ISSUE TITLE
Scenario Creator 

### ISSUE THREAD

**Issue by thedarktower52** [PurpleKingdomGames/virtual-gloomhaven-board#79]
**Affected Scenario(s):** Scenario Creator and .json files

**Describe the bug**
Scenario Creator is not aligning map tiles correctly. Also, when importing previously created .json files, the map is pushed off the left side of the screen.

**To Reproduce**
1. Start a new scenario in Scenario Creator
2. Place/rotate map tiles to see that they do not line up on connectors as they should
3. Export then import .json file of the map

**Browser :** Chrome 94.0.4606.54
[Scenario Creator.zip](https://github.com/PurpleKingdomGames/virtual-gloomhaven-board/files/7205869/Scenario.Creator.zip)

**Comment by hobnob** [comment]
Hi @thedarktower52 , thanks for letting me know. I'll have a look at this for you in the coming weeks and let you know how it goes. The 2 files provided are perfect, and give me exactly what I need to track this issue down 🙂

**Comment by hobnob** [comment]
The importation fix should now be in place with the latest release (`1.13.0`)
