### ISSUE TITLE
Unable to summon Hail for scenario 104 A Gaping Wound

### ISSUE THREAD

**Issue by cafelizardo** [PurpleKingdomGames/virtual-gloomhaven-board#82]
**Affected Scenario(s):** [e.g. 6, 10 and 33]

Scenario 104 A Gaping Wound from Forgotten Circles expansion

**Describe the bug**

Unable to summon Hail.

**To Reproduce**
1. Bring up scenario 104
2. Try to summon Hail.  Not listed.  Tried to use barrow but then can't drag barrow, had to create new barrow and delete old barrow each time she moves

**Browser :** [e.g. Chrome, Firefox]

Tried Safari, Firefox and Chrome.

**Comment by hobnob** [comment]
Hi @cafelizardo ! Just so I can understand this properly, would summoning a Summons work? Hail is represented by a numbered token on the board, so I'm struggling to find a suitable graphic at the moment (I have one in mind, but I'm unsure of the licensing)

**Comment by cafelizardo** [comment]
Yes, a regular summon would work.  Sorry I see that I can now do that.  I thought we had tried that, not sure how we missed that.

As for labeling, it would be nice if we could select the a label other than a sequential number.  Also it would be nice if we could select different colors for a summon based on the character class.  Currently our group has had a need to do a summon but we thought it might be a problem in the future.

**Comment by hobnob** [comment]
Ok, that's good to know - If I can't get hold of the image I need I'll close this issue and suggest using summons (though I think a preferred approach would be to have a Hail specific image). I'm planning a new release and I think it's probably time to add multiple summons colours. Initially I was thinking of allowing players to choose a colour, but actually it might be as simple as giving 5 Summons options and let people choose one 🤔

**Comment by cafelizardo** [comment]
If you can allow us to select different colored summons that would suffice. Better would be to allow different images for Hail and I believe there were some other scenarios where we had to escort other characters like villagers or prisoners, etc.  The main thing is so we don't have to use a different symbol like a barrel which can't be dragged around the map.

**Comment by hobnob** [comment]
Hi @cafelizardo ! There are a few new amends released today that should help with this:
 * You can now choose a summons colour - choose a colour from the settings and the next summons will be that colour
 * You can now place tokens on the board (a - f, 0 - 6)

Additionally I found a bug in Chrome that stops you dragging obstacles, which I've now fixed
I'm going to close the issue, as I *think* that solves the problems you were having - though I agree the ideal solution would be for every NPC to have their own portrait.. might have to search the internet one day and see if I can find anything suitable 🙂

**Comment by cafelizardo** [comment]
confirmed can now place tokens and label 0-6,a-f and summon though have to use 3-bar menu->Settings to change colors.  A bit awkward but but usable.  Don't see a way to change the label of a summon however, seems to keep incrementing.  Each class can only summon a single summon so that won't be a problem.  Can use this to summon multiple objectives or villagers, etc.  Thanks!
