### ISSUE TITLE
wrong trap and monster ID automatically spawned during scenario 111

### ISSUE THREAD

**Issue by cafelizardo** [PurpleKingdomGames/virtual-gloomhaven-board#85]
**Affected Scenario(s):**

scenario 111 - The Shackels loosen

**Describe the bug**

1) In the first room, there is a cluster of traps in the upper left corner.  Setup should be two damage traps and a disarm trap but virtual Gloomhaven board shows 3 damage traps.  Work around is to remove the extra damage trap and replace with the correct trap.

2) 2nd room, an Aesther scout appears near the top of the map with ID 6 however there are only 4 in the game.  Work around is to remove id 6 and spawn a new one which knows to only allow 1-4.

**To Reproduce**
1. Load scenario 111
2. You should see the wrong trap in the upper left corner.
3. Open north door
4. Observer scout near top with wrong ID.

**Browser :** [e.g. Chrome, Firefox]

Safari and Chrome.  Did not try Firefox.

**Comment by hobnob** [comment]
That's annoying, I've literally just done a release 😛 
Shouldn't be hard to fix though - I'll have a look and get a fix out for this tomorrow or Wednesday

**Comment by cafelizardo** [comment]
confirmed fix with version 1.14.1.  Thanks!
