### ISSUE TITLE
Wrong rooms for scenario 113

### ISSUE THREAD

**Issue by cafelizardo** [PurpleKingdomGames/virtual-gloomhaven-board#88]
**Affected Scenario(s):** [e.g. 6, 10 and 33]

Scenario 113 The Lost Thread

**Describe the bug**

The wrong rooms are displayed on the far left side of the map.  Room L3b should be at top left but is shown on lower left side of the map. Room L2a should be at the Bottom but is shown at the top left.  The two left most rooms are transposed. 

in the top and bottom rooms, the wrong rooms are displayed. When opening the left door in room J2B, room L3b is show instead of L2a.  Similarly when the left door in room J1b is opened room L2a is shown instead of room L3b.  The contents of the rooms are okay.  Only slight problem is the placement of the dark corridors are on the wrong sides.

**To Reproduce**
1. From starting room
2. Click on door at lower right side which reveals room J2b.
3. Click on door on left side which reveals room L3b which should be the top left room.
4. Click on dark corridor on bottom (which should be on top) which reveals room above which should be room L3b but is shown as room L2a.

**Browser :** [e.g. Chrome, Firefox]

Safari 15.4 on OSX 12.3
Chrome on windows, don't know version.

**Comment by hobnob** [comment]
Hi @cafelizardo, Sorry for the later reply, it's been really busy here 🙁  This should be a relatively easy fix, I'll get it into the next release 🙂
