### ISSUE TITLE
Query String Customization Not Working

### ISSUE THREAD

**Issue by johnmaxh** [PurpleKingdomGames/virtual-gloomhaven-board#93]
**Affected Scenario(s):**
N/A

**Describe the bug**
It doesn't appear like the 'customization' section of the readme works. I've tried setting the scenario with a query string parameter and it still defaults to scenario 1 every time. I've also tried clearing cache but that doesn't make a difference.

**To Reproduce**
1. Go to https://vgb.purplekingdomgames.com/?scenario=4
2. Scenario should be set to 4, but still displays 1

**Browser :**
Chrome and Firefox

**Comment by hobnob** [comment]
Hi @johnmaxh , that's very odd, but yes, I can confirm that it doesn't currently work. I'll take a look and get it into the next release
